language: elixir
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3.2
    - otp_release: 19.0
      elixir: 1.3.2

sudo: false
before_script:
  - mix deps.get
script:
  - mix test

notifications:
    slack: star-way-backend:MWDN3krztzCtIO4AP9qMy8ze
    on_success: always
    on_failure: always